### ISSUE TITLE
spmc implementation

### ISSUE THREAD

**Issue by tower120** [tower120/rc_event_queue#2]
Implement spmc through dummy lock + EventQueue mut interfaces.

**Comment by vi** [comment]
> https://docs.rs/rc_event_queue/0.2.2/rc_event_queue/spmc/index.html

> Single consumer, multi producers.

Aren't "consumer" and "producer" confused there? I assumed "spmc" is abbreviation for "sinlge _producer_", not consumer.

**Comment by tower120** [comment]
It is not implemented yet. Soon will be. It will be SINGLE producer/writer.

**Comment by tower120** [comment]
Oh - that is typo. Thanks! I'll fix that.
